In [1]:
import pandas as pd

In [2]:
nba = pd.read_csv('nba.csv')

In [3]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
nba['Sport']='Basketball' #Adds a new column named Sports and filling it with Basketball.

In [7]:
nba['Sport']

0      Basketball
1      Basketball
2      Basketball
3      Basketball
4      Basketball
5      Basketball
6      Basketball
7      Basketball
8      Basketball
9      Basketball
10     Basketball
11     Basketball
12     Basketball
13     Basketball
14     Basketball
15     Basketball
16     Basketball
17     Basketball
18     Basketball
19     Basketball
20     Basketball
21     Basketball
22     Basketball
23     Basketball
24     Basketball
25     Basketball
26     Basketball
27     Basketball
28     Basketball
29     Basketball
          ...
428    Basketball
429    Basketball
430    Basketball
431    Basketball
432    Basketball
433    Basketball
434    Basketball
435    Basketball
436    Basketball
437    Basketball
438    Basketball
439    Basketball
440    Basketball
441    Basketball
442    Basketball
443    Basketball
444    Basketball
445    Basketball
446    Basketball
447    Basketball
448    Basketball
449    Basketball
450    Basketball
451    Basketball
452    Basketball
453    Basketball
454    Basketball
455    Basketball
456    Basketball
457    Basketball
Name: Sport, Length: 458, dtype: object

In [8]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball

In [9]:
nba['League']='National Basketball Association'

In [11]:
nba.get('League')

0      National Basketball Association
1      National Basketball Association
2      National Basketball Association
3      National Basketball Association
4      National Basketball Association
5      National Basketball Association
6      National Basketball Association
7      National Basketball Association
8      National Basketball Association
9      National Basketball Association
10     National Basketball Association
11     National Basketball Association
12     National Basketball Association
13     National Basketball Association
14     National Basketball Association
15     National Basketball Association
16     National Basketball Association
17     National Basketball Association
18     National Basketball Association
19     National Basketball Association
20     National Basketball Association
21     National Basketball Association
22     National Basketball Association
23     National Basketball Association
24     National Basketball Association
25     National Basketball Association
26     National Basketball Association
27     National Basketball Association
28     National Basketball Association
29     National Basketball Association
                    ...
428    National Basketball Association
429    National Basketball Association
430    National Basketball Association
431    National Basketball Association
432    National Basketball Association
433    National Basketball Association
434    National Basketball Association
435    National Basketball Association
436    National Basketball Association
437    National Basketball Association
438    National Basketball Association
439    National Basketball Association
440    National Basketball Association
441    National Basketball Association
442    National Basketball Association
443    National Basketball Association
444    National Basketball Association
445    National Basketball Association
446    National Basketball Association
447    National Basketball Association
448    National Basketball Association
449    National Basketball Association
450    National Basketball Association
451    National Basketball Association
452    National Basketball Association
453    National Basketball Association
454    National Basketball Association
455    National Basketball Association
456    National Basketball Association
457    National Basketball Association
Name: League, Length: 458, dtype: object

### Recommended:

In [14]:
nba1 = pd.read_csv('nba.csv')

In [15]:
nba1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [16]:
nba1.insert(loc=3,column='Sports', value='Basketball') #insert is used to add columns as specific location. Shift+tab for more info

In [17]:
nba1

,Name,Team,Number,Sports,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,Basketball,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,Basketball,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,Basketball,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,Basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,Basketball,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,Basketball,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,Basketball,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,Basketball,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,Basketball,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,Basketball,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,Basketball,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,Basketball,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,Basketball,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,Basketball,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,Basketball,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,Basketball,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,Basketball,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,Basketball,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,Basketball,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,Basketball,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,Basketball,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,Basketball,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,Basketball,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,Basketball,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,Basketball,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,Basketball,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,Basketball,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,Basketball,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,Basketball,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,Basketball,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,Basketball,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,Basketball,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,Basketball,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,Basketball,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,Basketball,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,Basketball,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,Basketball,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,Basketball,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,Basketball,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,Basketball,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,Basketball,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,Basketball,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,Basketball,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,Basketball,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,Basketball,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,Basketball,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,Basketball,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,Basketball,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,Basketball,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,Basketball,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,Basketball,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,Basketball,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,Basketball,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,Basketball,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,Basketball,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,Basketball,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,Basketball,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,Basketball,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,Basketball,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN,NaN,NaN